services: 
  automatic1111:
    image: automatic1111
    container_name: automatic1111
    restart: always
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    volumes:
      - ./models:/stable-diffusion-webui/models/Stable-diffusion
    devices:
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia0
    command: -f --api --listen