services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports: [ "8888:8080" ]
    volumes:
      - ${SEARXNG_CONFIG}:/etc/searxng
      - ${SEARXNG_DATA}:/var/cache/searxng
    networks: 
      - selfhost_network

networks:
  selfhost_network:
    driver: bridge